### ISSUE TITLE
v1.2.1.0 - few suggestions and cosmetic bugs

### ISSUE THREAD

**Issue by kamilmirza** [jboughton/ManHole#2]
suggestions:
- option to autostart (ManHole) on startup
- ManHole should appear on single-click tray icon and should disappear when clicked outside 

bugs:
- on first run (after setup) pihole admin URL shows **pi.hole/admin** and not the configured one
- on right-click tray icon, its shows up on taskbar with icon only (no title)
- on right-click tray icon, options does not disappear when cursor is moved outside (without hovering the options)
- on double right-click, it shows ManHole main window
- when Auto-Refresh is Disabled from tray icon, main window shows **Auto-Refresh: Disabled** in green color

UPDATE:

- while tinkering it crashed with [THIS](https://hastebin.com/gabiloqena.sql) error
- getting Not Responding when pihole is disabled and pressing Refresh Manually multiple times
- on starting ManHole when pihole disabled its shows displays values like [THIS](https://i.imgur.com/YZZemwZ.png)

**Comment by jboughton** [comment]
- I've updated the latest release to include an optional autostart (current user only).
- The plan for the future is to have the stat window appear when hovering your mouse over the tray icon, and close automatically when the mouse leaves the icon.

The click behaviors are largely intentional, for now anyway.

There may have been an issue on your end preventing the saving of settings on your first run. Can you confirm that it worked after?

I have released an update fixing the auto-refresh button color bug. I have also fixed the exception caused when you were tinkering (related to a ShellExec when clicking recently blocked). These issues are fixed in 1.2.2.0.

I don't suggest refreshing manually frequently. This causes the Pi to become unresponsive for a time, which will in turn cause ManHole to fail to work properly.

The values you see when starting with the Pi-hole disabled are the placeholder values for those strings. The alternative would be to display an empty string (aka nothing), but keeping it like this helps me when arranging items in the UI.

Thanks for the report and the requests. I'll keep improving things as I go. Check out the new update!
